### ISSUE TITLE
Figwheel auto-loading lags behind by one save

### ISSUE THREAD

**Issue by caleb** [arachne-framework/arachne-figwheel#1]
This bug seems to be caused by a  recent change to the arachne-figwheel module, since using the version of `arachne-figwheel` that is pulled in by the `enterprise-spa` template works fine.

I used the `arachne` command line script to create a new project with the `enterprise-spa` template. Then I updated the version of `arachne-figwheel` to be a newer one that I built on my system (0.1.0-master-0015-eb63703)

Then I start CIDER and launch the system with `(go)`, and I can access the SPA.

(My project is here: https://github.com/caleb/arachne-figwheel-bug)

The issue is that when I make a change to the .cljs file and perform a save, the browser reloads the file via figwheel (the clojure logo appears in the bottom left, and the network panel of the debugging window shows that the javascript file is accessed), but the page does not have the latest changes.

If I make *another* change and save, the browser refreshes the javascript file and shows the results of the first change I made.

It's like figwheel is lagging behind one FileSet's worth of changes.

Here's a video showing the problem in action (it's 49 seconds): https://vimeo.com/204766144

**Comment by levand** [comment]
Thanks Caleb! I actually noticed that myself last week and am working on a fix for it today. It's related to a change I made that will let the Figwheel component be an asset producer as well, so you can get figwheel goodness while serving up through the standard Pedestal port (which makes Figwheel substantially more useful).

The issue is a fairly subtle race condition in figwheel notifications, but I should have a fix in place sometime today (I think)

**Comment by caleb** [comment]
Excellent!

I had to update the arachne-figwheel module so I could try out the new `:css?` flag with my sass module. It worked perfectly! Changing a sass file automatically reloaded in my browser via figwheel!
